version: '3.8'
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=myappdb
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  app:
    build: .  # Asume que el Dockerfile está en la misma carpeta que el docker-compose.yml
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=mysql://root:secret@db:3306/myappdb  # Ajusta según sea necesario
    depends_on:
      - db
volumes:
  db-data:
