version: '3.8'
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=myappdb
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
volumes:
  db-data:
