version: '3.8'
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=myappdb
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  app:
    build: .
    ports:
      - "5432:5432"
    environment:
      - PORT=3000
      - DATABASE_URL=mysql://root:secret@db:3306/myappdb
    depends_on:
      - db
volumes:
  db-data:
